name: Build and publish container

permissions:
  id-token: write
  contents: read
  packages: write
  attestations: write

on:
  workflow_call:
    inputs:
      registry:
        type: string
        required: true
      image:
        type: string
        required: true
      appname:
        type: string
        required: true
    secrets:
      ghcr_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ${{ inputs.registry }}
      IMAGE: ${{ inputs.image }}
      APPNAME: ${{ inputs.appname }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        id: buildx

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr_token }}

      - name: Build and push
        id: build
        run: |
          while IFS=$'\t' read -r key value; do
            BUILD_ARGS+=("--build-arg" "${key^^}_VERSION=${value}")
          done < <(yq -r 'to_entries[] | "\(.key)\t\(.value)"' versions.yaml)

          export VERSION=$(yq -r .${APPNAME} versions.yaml)

          docker buildx build \
            --builder ${{ steps.buildx.outputs.name }} \
            --platform linux/amd64 \
            --provenance=mode=max \
            --metadata-file build-metadata.json \
            --cache-from type=gha,scope=local \
            --cache-to type=gha,mode=max,scope=local \
            "${BUILD_ARGS[@]}" \
            -t ${REGISTRY}/${IMAGE}:${VERSION} \
            -t ${REGISTRY}/${IMAGE}:latest \
            --push -f Containerfile .

          IMAGE_DIGEST=$(jq -r '.["containerimage.digest"]' build-metadata.json)
          echo "digest=$IMAGE_DIGEST" >> "$GITHUB_OUTPUT"

      - name: Attest container
        uses: actions/attest@v4
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Retag version/latest after sigstore bundle
        run: |
          export VERSION=$(yq -r .${{ inputs.appname }} versions.yaml)
          docker buildx imagetools create \
            -t ghcr.io/{{ github.repository_owner }}/${{ inputs.image }}:latest \
            ghcr.io/{{ github.repository_owner }}/${{ inputs.image }}@sha256:${{ steps.build.outputs.digest }}
          docker buildx imagetools create \
            -t ghcr.io/{{ github.repository_owner }}/${{ inputs.image }}:${VERSION} \
            ghcr.io/{{ github.repository_owner }}/${{ inputs.image }}@sha256:${{ steps.build.outputs.digest }}

